version: '3.4'

services:
  kantnprojektbackend:
    image: kantnprojektbackend
    build:
      context: .
      dockerfile: Dockerfile
    command: ["sh", "-c", "pip install debugpy -t /tmp && python /tmp/debugpy --wait-for-client --listen 0.0.0.0:5678 -m flask run --no-debugger --no-reload --host 0.0.0.0 --port 8002"]
    ports:
      - 8002:8002
      - 5678:5678
    environment:
      - FLASK_APP=manage.py
