version: '3'
services:
  web:
    build: .
    command: gunicorn -b 0.0.0.0:8000 todosapp.wsgi:application
    depends_on:
      - postgres
    volumes:
      - .:/usr/src/app
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgres://kantnprojekt@postgres/kantn
  postgres:
    image: postgres:13-alpine
    environment:
      POSTGRES_USER: kantn
      POSTGRES_DB: kantnprojekt